import { ButtonAuxo } from '@/components/ButtonAuxo'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from "next/router";
import Link from "next/link";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Auxo DevTest Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Image
            src="/AuxoFlights 2.png"
            alt="Auxo Logo"
            width={180}
            height={37}
            priority
          />
          <ButtonAuxo onClick={()=>{console.log('hola')}}>
            <Link href="/itineraries">Start</Link>
          </ButtonAuxo>
      </main>
    </>
  )
}
